/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cc8cdca1-e2bb-425d-98cf-2aaeefaea339",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_U4wslJ0MK",
    "aws_user_pools_web_client_id": "1or2the9uu9ch71nv3lbu1gg0a",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "zipcodes-dev",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://aak4vv7w5jdkpnixumtmufvwd4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
