/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4ff7bed1-4cec-4efa-82e8-819cbc3d1d0d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_zxR6SkxiZ",
    "aws_user_pools_web_client_id": "3gh8l65h9ou94haiae1792sn2a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ztr5zxfuerhwhb5p3celoaqsiu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "zipcodes-myweather",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
